[package]
name = "rustcalls"
version = "0.1.0"
authors = ["<shankun>"]
edition = "2018"
build = "build.rs"


[lib]
name = "rustcalls"
crate-type =["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[build-dependencies]

